import { defineConfig } from "vitepress";

export default defineConfig({
  title: "AnomaPay SDK",
  description:
    "Developer documentation for the @anonma/anomapay-sdk — the TypeScript SDK for building privacy-preserving payment applications on Anoma.",

  head: [["link", { rel: "icon", href: "/favicon.ico" }]],

  // The /api/ directory is generated by TypeDoc (npm run docs:api) and is not
  // committed to the repository. Ignore dead links there so the build succeeds
  // whether or not the API reference has been generated yet.
  ignoreDeadLinks: [/\/api\//],

  themeConfig: {
    logo: "/logo.svg",
    siteTitle: "AnomaPay SDK",

    nav: [
      { text: "Getting Started", link: "/getting-started/installation" },
      { text: "Concepts", link: "/concepts/key-hierarchy" },
      { text: "Guides", link: "/guides/private-transfer-app" },
      { text: "API Reference", link: "/api/" },
    ],

    sidebar: {
      "/getting-started/": [
        {
          text: "Getting Started",
          items: [
            { text: "Installation", link: "/getting-started/installation" },
            { text: "Quick Start", link: "/getting-started/quick-start" },
          ],
        },
      ],

      "/concepts/": [
        {
          text: "Concepts",
          items: [
            { text: "Key Hierarchy", link: "/concepts/key-hierarchy" },
            { text: "Pay Address", link: "/concepts/pay-address" },
            { text: "Transfers", link: "/concepts/transfers" },
          ],
        },
      ],

      "/guides/": [
        {
          text: "Guides",
          items: [
            {
              text: "Private Transfer App",
              link: "/guides/private-transfer-app",
            },
          ],
        },
      ],

      "/configuration": [
        {
          text: "Configuration",
          items: [{ text: "Config Reference", link: "/configuration" }],
        },
      ],

      "/api/": [
        {
          text: "API Reference",
          link: "/api/",
        },
      ],
    },

    socialLinks: [
      { icon: "github", link: "https://github.com/anoma/anomapay-sdk" },
    ],

    footer: {
      message: "Released under the MIT License.",
      copyright: "Copyright © Heliax Inc.",
    },

    search: {
      provider: "local",
    },

    editLink: {
      pattern:
        "https://github.com/anoma/anomapay-sdk/edit/main/docs/:path",
      text: "Edit this page on GitHub",
    },
  },
});
