/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AppRouteRouteImport } from "./routes/_app/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SignUpIndexRouteImport } from "./routes/sign-up/index";
import { Route as LoginIndexRouteImport } from "./routes/login/index";
import { Route as SignUpWalletRouteImport } from "./routes/sign-up/wallet";
import { Route as SignUpPasskeysRouteImport } from "./routes/sign-up/passkeys";
import { Route as LoginWalletRouteImport } from "./routes/login/wallet";
import { Route as AppWithdrawRouteImport } from "./routes/_app/withdraw";
import { Route as AppSendRouteImport } from "./routes/_app/send";
import { Route as AppRequestRouteImport } from "./routes/_app/request";
import { Route as AppDepositRouteImport } from "./routes/_app/deposit";
import { Route as AppDashboardRouteImport } from "./routes/_app/dashboard";
import { Route as AppPayReceiverRouteImport } from "./routes/_app/pay.$receiver";

const AppRouteRoute = AppRouteRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpIndexRoute = SignUpIndexRouteImport.update({
  id: "/sign-up/",
  path: "/sign-up/",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpWalletRoute = SignUpWalletRouteImport.update({
  id: "/sign-up/wallet",
  path: "/sign-up/wallet",
  getParentRoute: () => rootRouteImport,
} as any);
const SignUpPasskeysRoute = SignUpPasskeysRouteImport.update({
  id: "/sign-up/passkeys",
  path: "/sign-up/passkeys",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginWalletRoute = LoginWalletRouteImport.update({
  id: "/login/wallet",
  path: "/login/wallet",
  getParentRoute: () => rootRouteImport,
} as any);
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: "/withdraw",
  path: "/withdraw",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppSendRoute = AppSendRouteImport.update({
  id: "/send",
  path: "/send",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppRequestRoute = AppRequestRouteImport.update({
  id: "/request",
  path: "/request",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppDepositRoute = AppDepositRouteImport.update({
  id: "/deposit",
  path: "/deposit",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AppRouteRoute,
} as any);
const AppPayReceiverRoute = AppPayReceiverRouteImport.update({
  id: "/pay/$receiver",
  path: "/pay/$receiver",
  getParentRoute: () => AppRouteRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/dashboard": typeof AppDashboardRoute;
  "/deposit": typeof AppDepositRoute;
  "/request": typeof AppRequestRoute;
  "/send": typeof AppSendRoute;
  "/withdraw": typeof AppWithdrawRoute;
  "/login/wallet": typeof LoginWalletRoute;
  "/sign-up/passkeys": typeof SignUpPasskeysRoute;
  "/sign-up/wallet": typeof SignUpWalletRoute;
  "/login": typeof LoginIndexRoute;
  "/sign-up": typeof SignUpIndexRoute;
  "/pay/$receiver": typeof AppPayReceiverRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/dashboard": typeof AppDashboardRoute;
  "/deposit": typeof AppDepositRoute;
  "/request": typeof AppRequestRoute;
  "/send": typeof AppSendRoute;
  "/withdraw": typeof AppWithdrawRoute;
  "/login/wallet": typeof LoginWalletRoute;
  "/sign-up/passkeys": typeof SignUpPasskeysRoute;
  "/sign-up/wallet": typeof SignUpWalletRoute;
  "/login": typeof LoginIndexRoute;
  "/sign-up": typeof SignUpIndexRoute;
  "/pay/$receiver": typeof AppPayReceiverRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_app": typeof AppRouteRouteWithChildren;
  "/_app/dashboard": typeof AppDashboardRoute;
  "/_app/deposit": typeof AppDepositRoute;
  "/_app/request": typeof AppRequestRoute;
  "/_app/send": typeof AppSendRoute;
  "/_app/withdraw": typeof AppWithdrawRoute;
  "/login/wallet": typeof LoginWalletRoute;
  "/sign-up/passkeys": typeof SignUpPasskeysRoute;
  "/sign-up/wallet": typeof SignUpWalletRoute;
  "/login/": typeof LoginIndexRoute;
  "/sign-up/": typeof SignUpIndexRoute;
  "/_app/pay/$receiver": typeof AppPayReceiverRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/dashboard"
    | "/deposit"
    | "/request"
    | "/send"
    | "/withdraw"
    | "/login/wallet"
    | "/sign-up/passkeys"
    | "/sign-up/wallet"
    | "/login"
    | "/sign-up"
    | "/pay/$receiver";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/dashboard"
    | "/deposit"
    | "/request"
    | "/send"
    | "/withdraw"
    | "/login/wallet"
    | "/sign-up/passkeys"
    | "/sign-up/wallet"
    | "/login"
    | "/sign-up"
    | "/pay/$receiver";
  id:
    | "__root__"
    | "/"
    | "/_app"
    | "/_app/dashboard"
    | "/_app/deposit"
    | "/_app/request"
    | "/_app/send"
    | "/_app/withdraw"
    | "/login/wallet"
    | "/sign-up/passkeys"
    | "/sign-up/wallet"
    | "/login/"
    | "/sign-up/"
    | "/_app/pay/$receiver";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AppRouteRoute: typeof AppRouteRouteWithChildren;
  LoginWalletRoute: typeof LoginWalletRoute;
  SignUpPasskeysRoute: typeof SignUpPasskeysRoute;
  SignUpWalletRoute: typeof SignUpWalletRoute;
  LoginIndexRoute: typeof LoginIndexRoute;
  SignUpIndexRoute: typeof SignUpIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-up/": {
      id: "/sign-up/";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof SignUpIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-up/wallet": {
      id: "/sign-up/wallet";
      path: "/sign-up/wallet";
      fullPath: "/sign-up/wallet";
      preLoaderRoute: typeof SignUpWalletRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sign-up/passkeys": {
      id: "/sign-up/passkeys";
      path: "/sign-up/passkeys";
      fullPath: "/sign-up/passkeys";
      preLoaderRoute: typeof SignUpPasskeysRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/wallet": {
      id: "/login/wallet";
      path: "/login/wallet";
      fullPath: "/login/wallet";
      preLoaderRoute: typeof LoginWalletRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_app/withdraw": {
      id: "/_app/withdraw";
      path: "/withdraw";
      fullPath: "/withdraw";
      preLoaderRoute: typeof AppWithdrawRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/send": {
      id: "/_app/send";
      path: "/send";
      fullPath: "/send";
      preLoaderRoute: typeof AppSendRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/request": {
      id: "/_app/request";
      path: "/request";
      fullPath: "/request";
      preLoaderRoute: typeof AppRequestRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/deposit": {
      id: "/_app/deposit";
      path: "/deposit";
      fullPath: "/deposit";
      preLoaderRoute: typeof AppDepositRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/dashboard": {
      id: "/_app/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AppDashboardRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
    "/_app/pay/$receiver": {
      id: "/_app/pay/$receiver";
      path: "/pay/$receiver";
      fullPath: "/pay/$receiver";
      preLoaderRoute: typeof AppPayReceiverRouteImport;
      parentRoute: typeof AppRouteRoute;
    };
  }
}

interface AppRouteRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute;
  AppDepositRoute: typeof AppDepositRoute;
  AppRequestRoute: typeof AppRequestRoute;
  AppSendRoute: typeof AppSendRoute;
  AppWithdrawRoute: typeof AppWithdrawRoute;
  AppPayReceiverRoute: typeof AppPayReceiverRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDepositRoute: AppDepositRoute,
  AppRequestRoute: AppRequestRoute,
  AppSendRoute: AppSendRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppPayReceiverRoute: AppPayReceiverRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginWalletRoute: LoginWalletRoute,
  SignUpPasskeysRoute: SignUpPasskeysRoute,
  SignUpWalletRoute: SignUpWalletRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignUpIndexRoute: SignUpIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
