/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as BetaRouteImport } from "./routes/beta";
import { Route as AuthenticatedRouteRouteImport } from "./routes/_authenticated/route";
import { Route as AuthRouteRouteImport } from "./routes/_auth/route";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as AuthenticatedModalRouteRouteImport } from "./routes/_authenticated/_modal/route";
import { Route as AuthenticatedAppRouteRouteImport } from "./routes/_authenticated/_app/route";
import { Route as AuthSignUpIndexRouteImport } from "./routes/_auth/sign-up/index";
import { Route as AuthLoginIndexRouteImport } from "./routes/_auth/login/index";
import { Route as AuthenticatedModalWithdrawRouteImport } from "./routes/_authenticated/_modal/withdraw";
import { Route as AuthenticatedModalSendRouteImport } from "./routes/_authenticated/_modal/send";
import { Route as AuthenticatedModalDepositRouteImport } from "./routes/_authenticated/_modal/deposit";
import { Route as AuthenticatedAppTransactionsRouteImport } from "./routes/_authenticated/_app/transactions";
import { Route as AuthenticatedAppDashboardRouteImport } from "./routes/_authenticated/_app/dashboard";
import { Route as AuthSignUpWalletRouteImport } from "./routes/_auth/sign-up/wallet";
import { Route as AuthSignUpPasskeysRouteImport } from "./routes/_auth/sign-up/passkeys";
import { Route as AuthLoginWalletRouteImport } from "./routes/_auth/login/wallet";
import { Route as AuthLoginInAppRouteImport } from "./routes/_auth/login/in-app";
import { Route as AuthenticatedOverlayReceiptIdRouteImport } from "./routes/_authenticated/_overlay/receipt.$id";
import { Route as AuthenticatedModalPayRequestRouteImport } from "./routes/_authenticated/_modal/pay.request";
import { Route as AuthenticatedModalPayDataRouteImport } from "./routes/_authenticated/_modal/pay.$data";
import { Route as AuthenticatedModalClaimSeedRouteImport } from "./routes/_authenticated/_modal/claim.$seed";

const BetaRoute = BetaRouteImport.update({
  id: "/beta",
  path: "/beta",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: "/_auth",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedModalRouteRoute = AuthenticatedModalRouteRouteImport.update({
  id: "/_modal",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: "/_app",
  getParentRoute: () => AuthenticatedRouteRoute,
} as any);
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: "/sign-up/",
  path: "/sign-up/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthenticatedModalWithdrawRoute =
  AuthenticatedModalWithdrawRouteImport.update({
    id: "/withdraw",
    path: "/withdraw",
    getParentRoute: () => AuthenticatedModalRouteRoute,
  } as any);
const AuthenticatedModalSendRoute = AuthenticatedModalSendRouteImport.update({
  id: "/send",
  path: "/send",
  getParentRoute: () => AuthenticatedModalRouteRoute,
} as any);
const AuthenticatedModalDepositRoute =
  AuthenticatedModalDepositRouteImport.update({
    id: "/deposit",
    path: "/deposit",
    getParentRoute: () => AuthenticatedModalRouteRoute,
  } as any);
const AuthenticatedAppTransactionsRoute =
  AuthenticatedAppTransactionsRouteImport.update({
    id: "/transactions",
    path: "/transactions",
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any);
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: "/dashboard",
    path: "/dashboard",
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any);
const AuthSignUpWalletRoute = AuthSignUpWalletRouteImport.update({
  id: "/sign-up/wallet",
  path: "/sign-up/wallet",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthSignUpPasskeysRoute = AuthSignUpPasskeysRouteImport.update({
  id: "/sign-up/passkeys",
  path: "/sign-up/passkeys",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginWalletRoute = AuthLoginWalletRouteImport.update({
  id: "/login/wallet",
  path: "/login/wallet",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthLoginInAppRoute = AuthLoginInAppRouteImport.update({
  id: "/login/in-app",
  path: "/login/in-app",
  getParentRoute: () => AuthRouteRoute,
} as any);
const AuthenticatedOverlayReceiptIdRoute =
  AuthenticatedOverlayReceiptIdRouteImport.update({
    id: "/_overlay/receipt/$id",
    path: "/receipt/$id",
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedModalPayRequestRoute =
  AuthenticatedModalPayRequestRouteImport.update({
    id: "/pay/request",
    path: "/pay/request",
    getParentRoute: () => AuthenticatedModalRouteRoute,
  } as any);
const AuthenticatedModalPayDataRoute =
  AuthenticatedModalPayDataRouteImport.update({
    id: "/pay/$data",
    path: "/pay/$data",
    getParentRoute: () => AuthenticatedModalRouteRoute,
  } as any);
const AuthenticatedModalClaimSeedRoute =
  AuthenticatedModalClaimSeedRouteImport.update({
    id: "/claim/$seed",
    path: "/claim/$seed",
    getParentRoute: () => AuthenticatedModalRouteRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/beta": typeof BetaRoute;
  "/login/in-app": typeof AuthLoginInAppRoute;
  "/login/wallet": typeof AuthLoginWalletRoute;
  "/sign-up/passkeys": typeof AuthSignUpPasskeysRoute;
  "/sign-up/wallet": typeof AuthSignUpWalletRoute;
  "/dashboard": typeof AuthenticatedAppDashboardRoute;
  "/transactions": typeof AuthenticatedAppTransactionsRoute;
  "/deposit": typeof AuthenticatedModalDepositRoute;
  "/send": typeof AuthenticatedModalSendRoute;
  "/withdraw": typeof AuthenticatedModalWithdrawRoute;
  "/login": typeof AuthLoginIndexRoute;
  "/sign-up": typeof AuthSignUpIndexRoute;
  "/claim/$seed": typeof AuthenticatedModalClaimSeedRoute;
  "/pay/$data": typeof AuthenticatedModalPayDataRoute;
  "/pay/request": typeof AuthenticatedModalPayRequestRoute;
  "/receipt/$id": typeof AuthenticatedOverlayReceiptIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/beta": typeof BetaRoute;
  "/login/in-app": typeof AuthLoginInAppRoute;
  "/login/wallet": typeof AuthLoginWalletRoute;
  "/sign-up/passkeys": typeof AuthSignUpPasskeysRoute;
  "/sign-up/wallet": typeof AuthSignUpWalletRoute;
  "/dashboard": typeof AuthenticatedAppDashboardRoute;
  "/transactions": typeof AuthenticatedAppTransactionsRoute;
  "/deposit": typeof AuthenticatedModalDepositRoute;
  "/send": typeof AuthenticatedModalSendRoute;
  "/withdraw": typeof AuthenticatedModalWithdrawRoute;
  "/login": typeof AuthLoginIndexRoute;
  "/sign-up": typeof AuthSignUpIndexRoute;
  "/claim/$seed": typeof AuthenticatedModalClaimSeedRoute;
  "/pay/$data": typeof AuthenticatedModalPayDataRoute;
  "/pay/request": typeof AuthenticatedModalPayRequestRoute;
  "/receipt/$id": typeof AuthenticatedOverlayReceiptIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_auth": typeof AuthRouteRouteWithChildren;
  "/_authenticated": typeof AuthenticatedRouteRouteWithChildren;
  "/beta": typeof BetaRoute;
  "/_authenticated/_app": typeof AuthenticatedAppRouteRouteWithChildren;
  "/_authenticated/_modal": typeof AuthenticatedModalRouteRouteWithChildren;
  "/_auth/login/in-app": typeof AuthLoginInAppRoute;
  "/_auth/login/wallet": typeof AuthLoginWalletRoute;
  "/_auth/sign-up/passkeys": typeof AuthSignUpPasskeysRoute;
  "/_auth/sign-up/wallet": typeof AuthSignUpWalletRoute;
  "/_authenticated/_app/dashboard": typeof AuthenticatedAppDashboardRoute;
  "/_authenticated/_app/transactions": typeof AuthenticatedAppTransactionsRoute;
  "/_authenticated/_modal/deposit": typeof AuthenticatedModalDepositRoute;
  "/_authenticated/_modal/send": typeof AuthenticatedModalSendRoute;
  "/_authenticated/_modal/withdraw": typeof AuthenticatedModalWithdrawRoute;
  "/_auth/login/": typeof AuthLoginIndexRoute;
  "/_auth/sign-up/": typeof AuthSignUpIndexRoute;
  "/_authenticated/_modal/claim/$seed": typeof AuthenticatedModalClaimSeedRoute;
  "/_authenticated/_modal/pay/$data": typeof AuthenticatedModalPayDataRoute;
  "/_authenticated/_modal/pay/request": typeof AuthenticatedModalPayRequestRoute;
  "/_authenticated/_overlay/receipt/$id": typeof AuthenticatedOverlayReceiptIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/beta"
    | "/login/in-app"
    | "/login/wallet"
    | "/sign-up/passkeys"
    | "/sign-up/wallet"
    | "/dashboard"
    | "/transactions"
    | "/deposit"
    | "/send"
    | "/withdraw"
    | "/login"
    | "/sign-up"
    | "/claim/$seed"
    | "/pay/$data"
    | "/pay/request"
    | "/receipt/$id";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/beta"
    | "/login/in-app"
    | "/login/wallet"
    | "/sign-up/passkeys"
    | "/sign-up/wallet"
    | "/dashboard"
    | "/transactions"
    | "/deposit"
    | "/send"
    | "/withdraw"
    | "/login"
    | "/sign-up"
    | "/claim/$seed"
    | "/pay/$data"
    | "/pay/request"
    | "/receipt/$id";
  id:
    | "__root__"
    | "/"
    | "/_auth"
    | "/_authenticated"
    | "/beta"
    | "/_authenticated/_app"
    | "/_authenticated/_modal"
    | "/_auth/login/in-app"
    | "/_auth/login/wallet"
    | "/_auth/sign-up/passkeys"
    | "/_auth/sign-up/wallet"
    | "/_authenticated/_app/dashboard"
    | "/_authenticated/_app/transactions"
    | "/_authenticated/_modal/deposit"
    | "/_authenticated/_modal/send"
    | "/_authenticated/_modal/withdraw"
    | "/_auth/login/"
    | "/_auth/sign-up/"
    | "/_authenticated/_modal/claim/$seed"
    | "/_authenticated/_modal/pay/$data"
    | "/_authenticated/_modal/pay/request"
    | "/_authenticated/_overlay/receipt/$id";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthRouteRoute: typeof AuthRouteRouteWithChildren;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
  BetaRoute: typeof BetaRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/beta": {
      id: "/beta";
      path: "/beta";
      fullPath: "/beta";
      preLoaderRoute: typeof BetaRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_auth": {
      id: "/_auth";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated/_modal": {
      id: "/_authenticated/_modal";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedModalRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/_app": {
      id: "/_authenticated/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_auth/sign-up/": {
      id: "/_auth/sign-up/";
      path: "/sign-up";
      fullPath: "/sign-up";
      preLoaderRoute: typeof AuthSignUpIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/login/": {
      id: "/_auth/login/";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof AuthLoginIndexRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_authenticated/_modal/withdraw": {
      id: "/_authenticated/_modal/withdraw";
      path: "/withdraw";
      fullPath: "/withdraw";
      preLoaderRoute: typeof AuthenticatedModalWithdrawRouteImport;
      parentRoute: typeof AuthenticatedModalRouteRoute;
    };
    "/_authenticated/_modal/send": {
      id: "/_authenticated/_modal/send";
      path: "/send";
      fullPath: "/send";
      preLoaderRoute: typeof AuthenticatedModalSendRouteImport;
      parentRoute: typeof AuthenticatedModalRouteRoute;
    };
    "/_authenticated/_modal/deposit": {
      id: "/_authenticated/_modal/deposit";
      path: "/deposit";
      fullPath: "/deposit";
      preLoaderRoute: typeof AuthenticatedModalDepositRouteImport;
      parentRoute: typeof AuthenticatedModalRouteRoute;
    };
    "/_authenticated/_app/transactions": {
      id: "/_authenticated/_app/transactions";
      path: "/transactions";
      fullPath: "/transactions";
      preLoaderRoute: typeof AuthenticatedAppTransactionsRouteImport;
      parentRoute: typeof AuthenticatedAppRouteRoute;
    };
    "/_authenticated/_app/dashboard": {
      id: "/_authenticated/_app/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport;
      parentRoute: typeof AuthenticatedAppRouteRoute;
    };
    "/_auth/sign-up/wallet": {
      id: "/_auth/sign-up/wallet";
      path: "/sign-up/wallet";
      fullPath: "/sign-up/wallet";
      preLoaderRoute: typeof AuthSignUpWalletRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/sign-up/passkeys": {
      id: "/_auth/sign-up/passkeys";
      path: "/sign-up/passkeys";
      fullPath: "/sign-up/passkeys";
      preLoaderRoute: typeof AuthSignUpPasskeysRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/login/wallet": {
      id: "/_auth/login/wallet";
      path: "/login/wallet";
      fullPath: "/login/wallet";
      preLoaderRoute: typeof AuthLoginWalletRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_auth/login/in-app": {
      id: "/_auth/login/in-app";
      path: "/login/in-app";
      fullPath: "/login/in-app";
      preLoaderRoute: typeof AuthLoginInAppRouteImport;
      parentRoute: typeof AuthRouteRoute;
    };
    "/_authenticated/_overlay/receipt/$id": {
      id: "/_authenticated/_overlay/receipt/$id";
      path: "/receipt/$id";
      fullPath: "/receipt/$id";
      preLoaderRoute: typeof AuthenticatedOverlayReceiptIdRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    "/_authenticated/_modal/pay/request": {
      id: "/_authenticated/_modal/pay/request";
      path: "/pay/request";
      fullPath: "/pay/request";
      preLoaderRoute: typeof AuthenticatedModalPayRequestRouteImport;
      parentRoute: typeof AuthenticatedModalRouteRoute;
    };
    "/_authenticated/_modal/pay/$data": {
      id: "/_authenticated/_modal/pay/$data";
      path: "/pay/$data";
      fullPath: "/pay/$data";
      preLoaderRoute: typeof AuthenticatedModalPayDataRouteImport;
      parentRoute: typeof AuthenticatedModalRouteRoute;
    };
    "/_authenticated/_modal/claim/$seed": {
      id: "/_authenticated/_modal/claim/$seed";
      path: "/claim/$seed";
      fullPath: "/claim/$seed";
      preLoaderRoute: typeof AuthenticatedModalClaimSeedRouteImport;
      parentRoute: typeof AuthenticatedModalRouteRoute;
    };
  }
}

interface AuthRouteRouteChildren {
  AuthLoginInAppRoute: typeof AuthLoginInAppRoute;
  AuthLoginWalletRoute: typeof AuthLoginWalletRoute;
  AuthSignUpPasskeysRoute: typeof AuthSignUpPasskeysRoute;
  AuthSignUpWalletRoute: typeof AuthSignUpWalletRoute;
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute;
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute;
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginInAppRoute: AuthLoginInAppRoute,
  AuthLoginWalletRoute: AuthLoginWalletRoute,
  AuthSignUpPasskeysRoute: AuthSignUpPasskeysRoute,
  AuthSignUpWalletRoute: AuthSignUpWalletRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
};

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
);

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute;
  AuthenticatedAppTransactionsRoute: typeof AuthenticatedAppTransactionsRoute;
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppTransactionsRoute: AuthenticatedAppTransactionsRoute,
};

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  );

interface AuthenticatedModalRouteRouteChildren {
  AuthenticatedModalDepositRoute: typeof AuthenticatedModalDepositRoute;
  AuthenticatedModalSendRoute: typeof AuthenticatedModalSendRoute;
  AuthenticatedModalWithdrawRoute: typeof AuthenticatedModalWithdrawRoute;
  AuthenticatedModalClaimSeedRoute: typeof AuthenticatedModalClaimSeedRoute;
  AuthenticatedModalPayDataRoute: typeof AuthenticatedModalPayDataRoute;
  AuthenticatedModalPayRequestRoute: typeof AuthenticatedModalPayRequestRoute;
}

const AuthenticatedModalRouteRouteChildren: AuthenticatedModalRouteRouteChildren =
  {
    AuthenticatedModalDepositRoute: AuthenticatedModalDepositRoute,
    AuthenticatedModalSendRoute: AuthenticatedModalSendRoute,
    AuthenticatedModalWithdrawRoute: AuthenticatedModalWithdrawRoute,
    AuthenticatedModalClaimSeedRoute: AuthenticatedModalClaimSeedRoute,
    AuthenticatedModalPayDataRoute: AuthenticatedModalPayDataRoute,
    AuthenticatedModalPayRequestRoute: AuthenticatedModalPayRequestRoute,
  };

const AuthenticatedModalRouteRouteWithChildren =
  AuthenticatedModalRouteRoute._addFileChildren(
    AuthenticatedModalRouteRouteChildren,
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren;
  AuthenticatedModalRouteRoute: typeof AuthenticatedModalRouteRouteWithChildren;
  AuthenticatedOverlayReceiptIdRoute: typeof AuthenticatedOverlayReceiptIdRoute;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
  AuthenticatedModalRouteRoute: AuthenticatedModalRouteRouteWithChildren,
  AuthenticatedOverlayReceiptIdRoute: AuthenticatedOverlayReceiptIdRoute,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BetaRoute: BetaRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
