name: Build Anoma App SDK
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CI: false
jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      VERSION: ${{ steps.set-environment-variables.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.REF }}
      - name: Set environment variables
        id: set-environment-variables
        run: |
          COMMIT_HASH=$(git rev-parse --short $SHA)
          BASE_VERSION=$(node -e 'console.log(require("./package.json").version)')
          echo "VERSION=v$BASE_VERSION-$COMMIT_HASH" >> "$GITHUB_OUTPUT"
        env:
          SHA: ${{ github.sha }}
      # - name: Print workflow inputs
      #   uses: ./.github/actions/print-workflow-inputs

  build-sdk:
    needs: setup
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.REF }}
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Rust dependencies
        uses: ./.github/actions/prepare-rust

      - name: Lint source check
        working-directory: ./
        run: pnpm lint

      - name: Build the Rust wasm library
        working-directory: ./
        run: pnpm build:wasm

      - name: Install Rust dependencies
        uses: ./.github/actions/prepare-build

      - name: Lint source check
        working-directory: ./
        env:
          SHA: ${{ github.sha }}
        run: pnpm lint

      - name: Build the Rust wasm library
        working-directory: ./
        env:
          SHA: ${{ github.sha }}
        run: pnpm build:wasm

      - name: Build the SDK
        working-directory: ./
        run: pnpm build

      - name: Run SDK unit tests
        working-directory: ./
        run: pnpm test

      - name: Pack the SDK
        working-directory: ./
        run: pnpm pack:ci

      - uses: actions/upload-artifact@v4
        with:
          name: anoma-app-sdk package archive
          path: ./package/anomaorg-anoma-app-sdk-*.tgz

  # TODO: This should ONLY happen when release-please PR is merged
  # release:
  #   needs: [setup, build-sdk]
  #   runs-on: ubuntu-24.04
  #   steps:
  #     - name: Download SDK build
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: anomaorg-anoma-app-sdk
  #         path: ./
  #
  #     - name: Get SDK Filename
  #       id: get-filenames
  #       run: |
  #         echo "SDK_FILENAME=$(ls -1 ./package)" >> "$GITHUB_OUTPUT"
  #
  #     - name: Make release body text
  #       run: |
  #         echo "ANOMA_APP_SDK_REVISION: $SHA" >> RELEASE
  #
  #     - name: Create release
  #       id: create-release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #       with:
  #         release_name: ${{ needs.setup.outputs.VERSION }}
  #         tag_name: ${{ needs.setup.outputs.VERSION }}
  #         body_path: ./RELEASE
  #
  #     - name: Add SDK archive to release
  #       uses: actions/upload-release-asset@v1
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #       with:
  #         upload_url: ${{ steps.create-release.outputs.upload_url }}
  #         asset_path: ./package/${{ steps.get-filenames.outputs.SDK_FILENAME }}
  #         asset_name: anomaorg-anoma-app-sdk_${{ needs.setup.outputs.version }}.zip
  #         asset_content_type: application/zip
