on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release

  publish-sdk:
    name: Publish Anoma App SDK to npm
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}

      - name: Build and Release Anoma App SDK
        uses: ./.github/actions/release-project
        with:
          tag: ${{ needs.release-please.outputs.sdk_tag }}
          bundle_filename: ${{ needs.release-please.outputs.sdk_tag }}.zip

      - uses: actions/setup-node@v4
        with:
          node-version: 24.x
          registry-url: "https://registry.npmjs.org"
        if: ${{ steps.release.outputs.release_created }}

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_ACCESS_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
